import type { Metadata } from "next";
import { Titillium_Web, Comfortaa} from "next/font/google";
import "./globals.css";
import PrelineScript from "@components/components/PrelineScript";

const comfortaa = Comfortaa({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>{children}</body>
      <PrelineScript></PrelineScript>
    </html>
  );
}
